server:
  http:
    addr: 0.0.0.0:8004
    timeout: 5s
  grpc:
    addr: 0.0.0.0:9004
    timeout: 5s

data:
  database:
    driver: postgres
    source: "user=admin password=root dbname=mydb port=5432 sslmode=disable"
  redis:
    network: tcp
    addr: "localhost:6379"
email:
  smtp_host: "smtp.gmail.com"
  smtp_port: 587
  username: "manoit2005@gmail.com"
  password: "wghn demk vzqv paxf"
  from: "manoit2005@gmail.com"

